apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebu-backend-deployment
spec:
  selector:
    matchLabels:
      app: rebu-backend
  template:
    metadata:
      labels:
        app: rebu-backend
      annotations:                                                              # Anotação para expor os endpoints ao Prometheus
        prometheus.io/scrape: "true"
    spec:
      restartPolicy: Always                                                     # Define politica para reiniciar o container em caso de falha

      containers:
      - name: rebu-backend
        image: rebu-backend:v1
        imagePullPolicy: IfNotPresent
        
        ports:
          - containerPort: 3001
            #hostPort: 3001
            protocol: TCP

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:                                                          # Configuração para verificação da saúde do container
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3001

        env:
        - name: JWT_SECRET
          value: "segredo_rebu"
        - name: ORS_API_KEY
          value: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImI5MjFlZWVhYjU3MDQ2ZDdiNTgwNzhlZWFmNDRkNGJjIiwiaCI6Im11cm11cjY0In0=

        - name: DB_HOST
          value: "database-service"
        - name: DB_NAME
          value: "rebu_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "food"
        - name: DB_PORT
          value: "5432"

        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
