# Permite número padrão de conexões do Nginx
events { 
    worker_connections: 1024
}

# Estabelece o tipo de servidor(http) e as regras de roteamento do serviço
http {
    upstream api_servers {
        server backend:3001;
        queue 10 timeout=2s
    }

    server {
        listen 80;
        server_name rebu.com.io;

        location / {
            proxy_pass http://api_servers;
            
            # Headers recomendados para repassar IPs e o Host originais ao backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}