apiVersion: app/v1
kind: Service
metadata:
  name: rebu-backend
spec:
  replicas: 1       # Número mínimo de instâncias do backend
  selector:
    app: rebu-backend
  template:
    spec:
      containers:
      - name: rebu-backend
        ports:
        - containerPort: 3001
        resources:
          request:
            cpu: "100m"
            memory: "128Mi"
          limit:
            cpu: "500m"
            memory: "2048Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          value: "segredo_rebu"
        - name: ORS_API_KEY
          value: "eyJvcmciOiI1YjNjZTM1OTg1MTEwMDFjZjYyNDgiLCJpZCI6ImI5MjFlZWVhYjU3MDQ2ZDdiNTgwNzhlZWFmNDRkNGJjIiwiaCI6Im11cm11cjY0In0="
        - name: DB_NAME
          value: "rebu"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "food"
        - name: DB_HOST
          value: "database"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 3

