version: "3.8"

services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3

    restart: unless-stopped

  database:
    image: postgres:18
    container_name: rebu-db

    environment:
      POSTGRES_DB: rebu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "food"

    ports:
      - "5432:5432"

    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 3

    restart: unless-stopped

  backend:
    image: rebu-backend:v1
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rebu-backend

    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3001:3001"

    env_file:
      - .env

    environment:
      NODE_ENV: development

      JWT_SECRET: "segredo_rebu"

      ORS_API_KEY: ${ORS_API_KEY}       # <<-- Lembrar de declarar no .env

      DB_NAME: rebu
      DB_USER: postgres
      DB_PASSWORD: "food"
      DB_HOST: database
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      database:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:3001/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npm run dev