name: rebu-application

include:
  - ../../backend/docker-compose.yaml

services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3
    restart: unless-stopped

  database:
    image: postgres:18
    container_name: rebu-db
    environment:
      POSTGRES_DB: rebu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "food"
    ports:
      - "5432:5432"
    volumes:
      - ../../backend/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 3
    restart: unless-stopped